### ISSUE TITLE
Release on rubygems.org

### ISSUE THREAD

**Issue by tompesman** [firmhouse/cardgate#7]
Thanks for this gem! I cannot find a release on rubygems.org, is this still expected?

Cheers!

**Comment by tompesman** [comment]
Is this project still maintained? I've issued a few PR's and there is no gem on rubgems.org.

**Comment by yourivdlans** [comment]
Hi Tom,

I will merge your PR's and put the gem on rubygems.org. Thanks for the work!

**Comment by tompesman** [comment]
Thanks! I'm also working on recurring charges for iDeal, but my Cardgate account is not yet enabled for that. I'll make a PR when it's ready.

**Comment by yourivdlans** [comment]
Sweet! If you need any help let me know.

**Comment by tompesman** [comment]
This is the commit: https://github.com/9to5/cardgate/commit/594af10f44f74c6e8a2f3d3e516badcbe276e6ca If you have a recurring enabled account you could test it. Otherwise I'll test it when my account is enabled.

**Comment by yourivdlans** [comment]
Looking good :) I also don't have an recurring enabled account.

**Comment by tompesman** [comment]
Thanks! Then we need to have some patience :wink:
